### ISSUE TITLE
Demo App: Tags aren't appearing in TagListView.

### ISSUE THREAD

**Issue by bfeher** [andreamazz/AMTagListView#20]
Hi, slick control!

I used `pod try AMTagListView` and chose option 2. I built using Xcode 6.1.1 (6A2008a), and ran using an iPhone 5s (8.1) simulator.

When hitting enter, the UITextField does empty, and the tag is created, but it never appears on screen.
After peeking under the hood I found this offending line of code:
![screen shot 2015-01-19 at 13 50 44](https://cloud.githubusercontent.com/assets/3466708/5796079/3b401700-9fe2-11e4-82c6-6528a1c7ec2e.png)

Is there a reason for this line? After removing it things work properly, but I feel shady just removing lines of code without fully understanding the entire project.

Awesome control btw, thanks for sharing it! :D

**Comment by bfeher** [comment]
Woops, so after digging around further, I see that the code above is necessary, and the real bug is here in AMViewController.m:
![screen shot 2015-01-19 at 14 45 57](https://cloud.githubusercontent.com/assets/3466708/5796367/016e800e-9fea-11e4-93f6-bf98f7a2a1a3.png)

I suspect there it should be `return ![text isEqualToString:@"bad"];`

**Comment by andreamazz** [comment]
Hi @bfeher 
Yup, my bad, that condition should be inverted, I'll fix it right away. Thanks!
