### ISSUE TITLE
Custom cell not selected

### ISSUE THREAD

**Issue by malkabani** [andreamazz/AMTagListView#21]
hi
i used Tags insde view inside table cell, but i can't select cell from table to get details (push to another view). and if i tap on cell (outSide of tagsView) work fine.

**Comment by andreamazz** [comment]
Hi @malkabani 
The selection is not triggered since the TagListView is an interactive view, make sure to disable user interaction on it, by using the `userInteractionEnabled` property

**Comment by toftof** [comment]
Hello @andreamazz , inhave the same problem. Looks like the setTapHandler is not triggered inside a tableviewcell. I have tried enabling the userinteraction property for both the cell and amtaglistview but still no luck. Pls advice. Thanks.

**Comment by andreamazz** [comment]
Try adding the taglistview to the cell itself, not to the contentView.

**Comment by toftof** [comment]
I have architectural requirements to keep the objects in contentview. Any guidance of how to achieve without adding to the cell directly?

Thanks.

**Comment by andreamazz** [comment]
The tags are basically `UIButton`s (i.e. there's a `UIButton` in their subviews), so the problem boils down to handle the tap of a common UIButton inside a view cell, it's not really relate with this library. I would suggest taking a look at [this SO thread](http://stackoverflow.com/questions/18866420/cant-click-uibutton-inside-a-cell-in-uitableview).

**Comment by toftof** [comment]
Perfect, thanks for the link.
