### ISSUE TITLE
There's a retain cycle problem that causes memory leaks in AMTagListView

### ISSUE THREAD

**Issue by Skogetroll** [andreamazz/AMTagListView#22]
### Brief intro ###
My app uses your control on each view controller in UIPageViewController. Recently, I detected that there’s a memory leak when scrolling in PageViewController.

I’ve used [CRChecker](https://github.com/duowan/CRChecker) to detect possible retain cycles and troublesome controls, and the analysis indeed shows that your control definitely has this problem.

### Possible sources ###

After brief source inspection I detected few possible sources:
* `- [AMTagListView setup]` contains this code:

        self.orientationNotification = [center addObserverForName:UIDeviceOrientationDidChangeNotification object:nil queue:nil usingBlock:^(NSNotification *note) {
            [self rearrangeTags];
        }];
            self.tagNotification = [center addObserverForName:AMTagViewNotification object:nil queue:nil usingBlock:^(NSNotification *notification) {
            if (self == notification.userInfo[@"superview"]) {
                if (_tapHandler) {
                    self.tapHandler(notification.object);
                }
            }
        }];

* `- [AMTagListView rearrangeTags]`  contains this one:

        [self.tags enumerateObjectsUsingBlock:^(AMTagView* obj, NSUInteger idx, BOOL *stop) {
        size = obj.frame.size;
        [self.subviews enumerateObjectsUsingBlock:^(UIView* obj, NSUInteger idx, BOOL *stop) {
            if ([obj isKindOfClass:[AMTagView class]]) {
                maxY = MAX(maxY, obj.frame.origin.y);
            }
        }];
        
        [self.subviews enumerateObjectsUsingBlock:^(UIView* obj, NSUInteger idx, BOOL *stop) {
            if ([obj isKindOfClass:[AMTagView class]]) {
                if (obj.frame.origin.y == maxY) {
                    maxX = MAX(maxX, obj.frame.origin.x + obj.frame.size.width);
                }
            }
        }];
        
        // Go to a new line if the tag won't fit
        if (size.width + maxX > (self.frame.size.width - self.marginX)) {
            maxY += size.height + self.marginY;
            maxX = 0;
        }
        obj.frame = (CGRect){maxX + self.marginX, maxY, size.width, size.height};
            [self addSubview:obj];
        }];

There is link to self in both `- [NSNotificationCenter addObserverForName:object:queue:usingBlock]` and `[NSArray enumerateObjectsUsingBlock:]`.
And blocks always retain all captured variables.

So now we have a strong reference to AMTagListView that [keeps that object in memory until the block object is deallocated](http://blackpixel.com/blog/2014/03/capturing-myself.html).

### Possible solution ###

You should pass [weak pointers to self](https://dhoerl.wordpress.com/2013/04/23/i-finally-figured-out-weakself-and-strongself/), instead of strong ones.

##### But … #####

I’m not sure that the problem is limited to these two cases, so you should check your code further for any other possible sources of memory leaks.

**Comment by mythodeia** [comment]
@Skogetroll something like this, right?
```
    __weak AMTagListView *weakSelf = self;
    self.orientationNotification = [center addObserverForName:UIDeviceOrientationDidChangeNotification object:nil queue:nil usingBlock:^(NSNotification *note) {
        [weakSelf rearrangeTags];
    }];
    self.tagNotification = [center addObserverForName:AMTagViewNotification object:nil queue:nil usingBlock:^(NSNotification *notification) {
        if (weakSelf == notification.userInfo[@"superview"]) {
            if (_tapHandler) {
                weakSelf.tapHandler(notification.object);
            }
        }
    }];
```

**Comment by andreamazz** [comment]
Weird that something like this flew over my head. So weird that I had to checkout the git blame and.... Yep, that was me. :smile:  
I'll fix it asap, thanks for the heads up
