### ISSUE TITLE
AMTagView bug: button frame is equal to CGRectZero

### ISSUE THREAD

**Issue by akhatmullin** [andreamazz/AMTagListView#25]
I don't know how I do this, but this is real mistake :)
![2015-02-11 13 26 12](https://cloud.githubusercontent.com/assets/2721609/6143878/c1f4ee6c-b1f1-11e4-9dd7-33fa81a793d4.png)

**Comment by andreamazz** [comment]
My bad, checkout latest commit for a fix.

**Comment by akhatmullin** [comment]
Thank you for operative support!
