### ISSUE TITLE
Button "Add tag" into AMTagListView

### ISSUE THREAD

**Issue by akhatmullin** [andreamazz/AMTagListView#27]
Many times me and our team open form where we using AMTagViewList with textfield. And always when we need input new tag we tap to AMTagViewList (this happening automaitcally, by instinct), not to textfield upper. Maybe we add button to add tag in AMTagListView ?

**Comment by andreamazz** [comment]
The list itself does not provide an input method by design. It's really a matter of preferences and of how your UI is structured, so this library is and will remain agnostic in that regard.
