### ISSUE TITLE
My view add about 300 tags, it take ~30MB RAM

### ISSUE THREAD

**Issue by buidinhnguyen** [andreamazz/AMTagListView#34]
Anyone meet it?

**Comment by andreamazz** [comment]
Hi @buidinhnguyen 
There was a possible minor leak, it should be fixed in the latest commit. As far as memory usage I don't think it'll go much under that size though.

**Comment by buidinhnguyen** [comment]
thanks @andreamazz I will check it out now.

**Comment by andreamazz** [comment]
Closing this for now. Let me know if the problem persists.
