### ISSUE TITLE
How to mirror the layout?

### ISSUE THREAD

**Issue by mohammad19991** [andreamazz/AMTagListView#35]

**Comment by andreamazz** [comment]
Can you elaborate?

**Comment by mohammad19991** [comment]
yea I mean showing the tags from right to left (alignment).

**Comment by andreamazz** [comment]
Ok, I see. Right now it's not possible, but it should be easy to implement. I'll keep you posted.

**Comment by mohammad19991** [comment]
@andreamazz thank you!

**Comment by andreamazz** [comment]
Hi @mohammad19991 
Checkout commit 753347d for the `tagAlignment` property. Set it to `AMTagAlignmentRight`.
Let me know if this fixes this issue the way you imagined. 

Cheers.
