### ISSUE TITLE
Swift 2 / iOS 9 support?

### ISSUE THREAD

**Issue by 3webbg** [andreamazz/AMTagListView#39]
Hello,
when it is expected to have support for iOS 9 / xcode 7 and Swift 2?
Thanks for the great library!

**Comment by andreamazz** [comment]
Uhm, it should work fine. Did you encounter any issue? Maybe I need to spruce up the demo project, but as a library it should work fine (it's objective-c after all).

**Comment by matibzurovski** [comment]
Hi, I am not able to set the appearance.
If I put the following code:
AMTagListView.appearance().radius = 10

I get "Value of type 'AMTagListView' has no member 'radius'." I am able to add tags properly though.

**Comment by andreamazz** [comment]
radius is a property of AMTagView, not AMTagListView

**Comment by matibzurovski** [comment]
Thanks! Other question: how do I get the width of a tag recently added? If I print AMTagView.tagLength it always prints 10, no matter what text does the tag contain.

**Comment by andreamazz** [comment]
`tagLength` is the length of the tag's tail, as [documented](https://github.com/andreamazz/AMTagListView/blob/master/Source/AMTagView.h#L28). 
If you need the full width you can simply use the tag's frame size, since it behaves as a normal `UIView`.

**Comment by andreamazz** [comment]
Closing this for now, let me know if you need more info.
