### ISSUE TITLE
How do I remove the 'tail' part of the AMTagView

### ISSUE THREAD

**Issue by goelv** [andreamazz/AMTagListView#40]
Firstly, thank you soo much for this great library. It's exactly what I need!!

I wouldn't like to have any 'tail' element for any of the AMTagView objects. How do I do this?

**Comment by andreamazz** [comment]
Hi @goelv 
tagLength set to 0 should do the trick. Let me know if itworks, I can't try right now because I'm afraid my eyes will pop off, but I'll be happy to check it out tomorrow.  

Glad this lib is helping you :+1:   

Cheers

**Comment by andreamazz** [comment]
BTW, I would also set holeRadius to 0 to avoid surprises.

**Comment by goelv** [comment]
Great thank worked like a charm!

Yes I already had put the holeRadius to 0.

**Comment by andreamazz** [comment]
Ace :+1:
