### ISSUE TITLE
Sending 'int' to parameter of incompatible type 'CGPoint' (aka 'struct CGPoint')

### ISSUE THREAD

**Issue by rjpalermo1** [andreamazz/AMTagListView#43]
Hello and first of all thank you for your work here.  I implemented this in a project I am working on and did a pod update and received this error on compile:

<img width="1181" alt="screen shot 2015-10-15 at 17 35 27" src="https://cloud.githubusercontent.com/assets/7153565/10515212/68542aec-7363-11e5-9f7b-4b1a5f2c3b6c.png">

**Comment by andreamazz** [comment]
https://github.com/andreamazz/AMTagListView/blob/master/CHANGELOG.md#090

`textPadding` is now a `CGPoint` to support both vertical and horizontal padding. Change to `CGPointMake(15, 15)`

**Comment by rjpalermo1** [comment]
Thank you!!!
