### ISSUE TITLE
Is there a way to add two different AMTagListView to one view controller?

### ISSUE THREAD

**Issue by kimi0421** [andreamazz/AMTagListView#45]

**Comment by andreamazz** [comment]
Sure, I see no problem in that.

**Comment by kimi0421** [comment]
So I just add two AMTagListView? and using [[AMTagView appearance] setTextPadding:CGPointMake(14, 14)] like that to have different properties?

**Comment by andreamazz** [comment]
If you set a property on the appearance proxy, the next object of that class that you instantiate will have those properties. If you want to have different properties you can set the properties directly on the instantiated object, something like:
```objc
self.otherTagView.textPadding = CGPointMake(10, 10);
```

**Comment by kimi0421** [comment]
I see, thank you so much

**Comment by andreamazz** [comment]
:+1:

**Comment by kimi0421** [comment]
But the problem is I found there is no such properties 
![image](https://cloud.githubusercontent.com/assets/3711468/11303755/800e3c2a-8fdf-11e5-8d54-beabb60be74d.png)

**Comment by kimi0421** [comment]
You can see it's not working.

**Comment by andreamazz** [comment]
Oh right, my bad, the text padding is a property of `AMTagView`.  
Ok, in that case you should probably set the text padding on the appearance proxy just before adding the tag in the appropriate list view

**Comment by kimi0421** [comment]
So you mean I can add two kinds of text padding on the appearance proxy?

**Comment by andreamazz** [comment]
You need to switch them when needed. Before adding a tag to the first view, set it to the padding you need, and the same for the second. 
I know it's not super intuitive.

**Comment by kimi0421** [comment]
I see, let me try, Thank you so much

**Comment by gmogames** [comment]
By the way, setting the properties before adding the tag does not work, the appearance of all tags will always be the last appearance you did. So If i change the background color of a tag before adding and change it again to add a new one, all tag will have the background color of the last one set.
