### ISSUE TITLE
Is there a way to detect when user removed a tag?

### ISSUE THREAD

**Issue by claudioredi** [andreamazz/AMTagListView#46]
I'm trying to notify some app class when a tag was deleted by user. I didn't find any event triggered when this happens so don't see you can detect it.

I could do the change and create a pull request in case it's not implemented and you think it could help other people.

Thanks

**Comment by andreamazz** [comment]
No, currently there is no way to tell. PRs are welcome. Did you implement a method in the delegate?

**Comment by claudioredi** [comment]
I haven't implemented anything yet, but adding a method in the delegate would be the best. Keep you posted.

Thanks

**Comment by claudioredi** [comment]
I may be crazy but I remember being able to delete tags clicking on them. I tested this some days ago but I'm quite sure I saw that. I'm no longer able to do so. Am I crazy? :)

**Comment by andreamazz** [comment]
Nope, you're right, I changed the sample to test another issue. You can however remove the last tag by clicking the right navbar button

**Comment by claudioredi** [comment]
I've finally used `AMTagViewNotification` to detect user tap over tag and delete it. Haven't changed anything on the code. Feel free to close this.

**Comment by andreamazz** [comment]
Cool :+1:

**Comment by IOSDeveloperProgrammer** [comment]
Hi, I am facing same problem. how to detect tag index ?? please tell me

**Comment by andreamazz** [comment]
Let me add a delegate method for this purpose, it'll be more clear.
I'll do it in the next few days.

**Comment by andreamazz** [comment]
And by next few days I mean now. Check out the latest commit and let me know if that works for you.

**Comment by andreamazz** [comment]
Released 1.4.0
