### ISSUE TITLE
support for multiple accessory images

### ISSUE THREAD

**Issue by nsolter** [andreamazz/AMTagListView#57]
It would be nice to be able to specify an array of images. Because I needed this for my current project, I hacked something up here: https://github.com/andreamazz/AMTagListView/compare/master...emmerge:multiple_images?expand=1 If this is of general interest, I can turn this into something that would be backwards compatible with the single accessory image for a pull request.

**Comment by andreamazz** [comment]
Hi @nsolter 
That would be really appreciated. Thanks for all your contributions, I'll make sure to get over the rest of the issues as soon as possible.

**Comment by nsolter** [comment]
Great, thanks! I'll work on this feature when I have some time, hopefully soon.

**Comment by nsolter** [comment]
I finally got around to cleaning this up and submitted the pull request.
