### ISSUE TITLE
Custom tag view

### ISSUE THREAD

**Issue by igormatyushkin014** [andreamazz/AMTagListView#60]
Developer should be able to use custom tag view, built from scratch, without subclassing `AMTagView`. This feature could bring much more flexibility to the library.

**Comment by andreamazz** [comment]
Hi @igormatyushkin014 
That's a good point. The implementation should be pretty easy too, I guess I can just extract the needed func calls in a protocol that the view needs to implement. How does that sound?

**Comment by igormatyushkin014** [comment]
@andreamazz Yeah, I like the idea with protocol.

**Comment by andreamazz** [comment]
@igormatyushkin014 
I've pushed some changes in the `develop` branch. You can now provide a UIView conforming to AMTag. 
The view must handle its own sizing.

Let me know if that works for you.

**Comment by andreamazz** [comment]
I'll take the silence as a "it's working". Reopen if something is broken.
